export const S = {
  bg: { minHeight: "100vh", background: "linear-gradient(135deg,#f2ede6,#e8f0e4)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Georgia',serif", padding: 20 },
  card: { background: "#fff", borderRadius: 20, padding: "48px 40px", width: "100%", maxWidth: 500, boxShadow: "0 8px 40px rgba(100,120,80,.10)" },
  title: { fontSize: 26, color: "#3a5a38", margin: "0 0 8px", fontWeight: "normal" },
  label: { display: "block", fontSize: 13, color: "#5a6e52", fontWeight: 600, marginBottom: 5 },
  muted: { fontSize: 12, color: "#a09880", margin: 0 },
  body: { fontSize: 15, color: "#4a4035", lineHeight: 1.7, margin: 0 },
  input: { width: "100%", padding: "10px 13px", fontSize: 14, fontFamily: "'Georgia',serif", border: "1.5px solid #d8d0c4", borderRadius: 10, background: "#faf8f5", color: "#3a3028", boxSizing: "border-box", lineHeight: 1.5 },
  btn: { display: "block", width: "100%", marginTop: 16, padding: "13px", background: "#5a8055", color: "#fff", border: "none", borderRadius: 12, fontSize: 15, fontFamily: "'Georgia',serif", cursor: "pointer" },
  btnSm: { padding: "7px 14px", background: "#5a8055", color: "#fff", border: "none", borderRadius: 8, fontSize: 13, fontFamily: "'Georgia',serif", cursor: "pointer" },
  btnDanger: { padding: "6px 12px", background: "#c0645a", color: "#fff", border: "none", borderRadius: 8, fontSize: 12, fontFamily: "'Georgia',serif", cursor: "pointer" },
  sidebar: { width: 215, background: "#fff", borderRight: "1px solid #e8e0d4", padding: "28px 14px", display: "flex", flexDirection: "column", gap: 2, minHeight: "100vh" },
  navBtn: { width: "100%", textAlign: "left", background: "none", border: "none", padding: "9px 11px", borderRadius: 9, fontSize: 13, fontFamily: "'Georgia',serif", color: "#6a5e50", cursor: "pointer", display: "flex", alignItems: "center" },
  navActive: { background: "#eef4ec", color: "#3a5a38", fontWeight: "bold" },
  sTitle: { fontSize: 20, color: "#3a5a38", fontWeight: "normal", marginBottom: 10, marginTop: 0 },
  card2: { background: "#f8f5f0", borderRadius: 12, padding: 18, marginBottom: 16 },
  entry: { background: "#fff", border: "1px solid #e4ddd4", borderRadius: 12, padding: "14px 18px", marginBottom: 10 },
  row: { display: "flex", gap: 10, alignItems: "center", marginBottom: 8 },
  tag: { background: "#eef4ec", color: "#3a5a38", borderRadius: 6, padding: "3px 9px", fontSize: 12, fontWeight: 600 },
  progress: { height: 10, borderRadius: 5, background: "#e0d8ce", overflow: "hidden", marginTop: 6 },
  progressBar: (pct, color = "#5a8055") => ({ height: "100%", width: `${Math.min(pct, 100)}%`, background: color, borderRadius: 5, transition: "width .4s" }),
};
